on:
  pull_request:

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ref: ${{ github.base_ref }}
            name: base
          - ref: ${{ github.head_ref }}
            name: head
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { execSync } = require("child_process");
            const result = execSync("bin/benchmark");
            const body = `
              ${{ matrix.name }} (${{ matrix.ref }})
              \`\`\`
              ${result}
              \`\`\`
            `;
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.rest.issues.createComment({ issue_number, owner, repo, body });
