on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - run: gem update --system
      - run: bundle exec rake generate
      - run: git diff --exit-code
